BEGIN TRANSACTION;
DROP TABLE IF EXISTS "tables";
CREATE TABLE IF NOT EXISTS "tables" (
	"id"	INTEGER NOT NULL,
	"state"	TEXT,
	"price"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "inventory";
CREATE TABLE IF NOT EXISTS "inventory" (
	"id"	INTEGER,
	"name"	TEXT,
	"price_huf"	INTEGER,
	"price_eur"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
DROP TABLE IF EXISTS "orders";
CREATE TABLE IF NOT EXISTS "orders" (
	"id"	INTEGER,
	"food_id"	INTEGER,
	"table_id"	INTEGER,
	PRIMARY KEY("id" AUTOINCREMENT)
);
COMMIT;
